### ISSUE TITLE
Selenium Recording and JIRA

### ISSUE THREAD

**Issue by skhanker** [ubc-library/webdriverIO-boilerplate#1]
Heya Schuyler, Rod,

You can close this issue, just wanted to send a related message to this project you guys have started.

If you are interested, I was doing some CI/CD test automation here at Beanworks, and we also used webdriverIO, and so I have a docker container that you can trigger to run, that will git pull in your webdriverIO project, run the tests, and do a screen recording of the test run, and uploads it to FTP. Choppiness of the video recording is inversely proportional to the amount of RAM on the server running Selenium.

We also made a JIRA project (lets call it PRODUCT) that has definitions for each test that needs to be defined. When we write a test, we start each block with the JIRA ticket, e.g. "PRODUCT-1 When loading homepage It must show a login page". When the tests run, if a test fails, we put a method in the webdriverIO onFail hook to create a ticket in our regular jira support project, but in the body of the ticket, we include the text of the test clause, and because JIRA automagically parses known tickets into links, your defect ticket gets linked to the product specification ticket, so you can reference what the exact product functionality spec was.

We can grab a beer to resolve this issue if ya like, or just grab a beer! Shoot me a text.

- skk

**Comment by schuyberg** [comment]
Yo! Just saw this (apparently my notification settings aren't too good..). Sounds like a rad setup. I've got webdriver set up with gitlab CI right now, and that process is working pretty well, but getting quite a few failures just due to lag from the site still, so any advice on optimizing webdriver would be great. Auto creating tickets sounds interesting too.. Definitely up for a beer some time soon. Be in touch!
